In [1]:
import pandas as pd
import numpy as np
import category_encoders as ce
import sklearn
from sklearn.model_selection import train_test_split

In [2]:
#Import the data
data = pd.read_csv("Data_trans_claims_fac.csv", encoding = "latin-1")
del data["Unnamed: 0"]
data.head()

,Total_Claims,FV_D,FV_M,FV_DATE,VISIT_CODE,WP_ID,WP_NAME,WP_ADDRESS,REGION_CODE,IND_Name,...,NAICS.DESCR,Frac_Level,LB_Level,Sh_Level,HIC_Level,HIC_Per_Level,Emp1524_Level,Emp2554_Level,Emp55plus_Level,Contra_level
0,951,23,10,2019-10-23,2019-10-23 2123905,2123905,Solutions CMD,"275 Daniel Street, Arnprior - Renfrew - Arnpri...",K,Construction,...,Industrial Building and Structure Construction,Low-Moderate,Low,Low,Moderate,Very High,Above Average,Above Average,Above Average,Moderate
1,951,8,1,2019-01-08,2019-01-08 2012482,2012482,D S CONSTRUCTION,"Listowel - Perth - North Perth, ON, CANADA LOT...",K,Construction,...,Residential Building Construction,Low-Moderate,Low,Low,Moderate,Very High,Above Average,Above Average,Above Average,Low
2,208,16,1,2019-01-16,2019-01-16 2055708,2055708,Foresterie Malloy Inc,"132 bisson Rang, Sherbrooke Township - Haldima...",K,"Agriculture, forestry, fishing and hunting",...,Contract Logging,Very Low,Very Low,Very Low,Very Low,Very High,Below Average,Below Average,Above Average,None
3,951,23,1,2019-01-23,2019-01-23 2056530,2056530,DEBUS DESIGN BUILD,"199, Stratford - Perth - Stratford, ON, CANADA...",K,Construction,...,Residential Building Construction,Low-Moderate,Low,Low,Moderate,Very High,Above Average,Above Average,Above Average,High
4,951,4,2,2019-02-04,2019-02-04 2058458,2058458,LANG CONTRACTING,"St. Marys - Perth - St. Marys, ON, CANADA 74 W...",K,Construction,...,Residential Building Construction,Low-Moderate,Low,Low,Moderate,Very High,Above Average,Above Average,Above Average,High

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27243 entries, 0 to 27242
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Total_Claims     27243 non-null  int64
 1   FV_D             27243 non-null  int64
 2   FV_M             27243 non-null  int64
 3   FV_DATE          27243 non-null  object
 4   VISIT_CODE       27243 non-null  object
 5   WP_ID            27243 non-null  int64
 6   WP_NAME          27243 non-null  object
 7   WP_ADDRESS       27243 non-null  object
 8   REGION_CODE      27243 non-null  object
 9   IND_Name         27243 non-null  object
 10  IND_Cat          27243 non-null  object
 11  IND              27243 non-null  object
 12  NAICS            27243 non-null  int64
 13  NAICS.DESCR      27243 non-null  object
 14  Frac_Level       27243 non-null  object
 15  LB_Level         27243 non-null  object
 16  Sh_Level         27243 non-null  object
 17  HIC_Level        27243 non-null  object
 18  HIC_Per_Level    27243 non-null  object
 19  Emp1524_Level    27243 non-null  object
 20  Emp2554_Level    27243 non-null  object
 21  Emp55plus_Level  27243 non-null  object
 22  Contra_level     27243 non-null  object
dtypes: int64(5), object(18)
memory usage: 4.8+ MB

In [60]:
data.isnull().sum()

Claims_Level       0
FV_D               0
FV_M               0
FV_DATE            0
VISIT_CODE         0
WP_ID              0
WP_NAME            0
WP_ADDRESS         0
REGION_CODE        0
IND_Name           0
IND_Cat            0
IND                0
NAICS              0
NAICS.DESCR        0
Frac_Level         0
LB_Level           0
Sh_Level           0
HIC_Level          0
HIC_Per_Level      0
Emp1524_Level      0
Emp2554_Level      0
Emp55plus_Level    0
Contra_level       0
dtype: int64

ENCODING CATEGORICAL VARIABLES

In [64]:
#Claims_level
enc_Claims_Code= ce.OrdinalEncoder(cols=['Claims_Level'], mapping=[{'col':'Claims_Level', 'mapping':{'Very Low':1, 'Low':2, 'Moderate':3, 'High':4, 'Very High':5}}])
data['Claims_Code'] = enc_Claims_code.fit_transform(data[['Claims_Level']])
del data['Claims_Level']

In [4]:
#REGION_CODE
enc_RegCode= ce.OrdinalEncoder(cols=['REGION_CODE'], mapping=[{'col':'REGION_CODE', 'mapping':{'K':1, 'L':2, 'M':3, 'N':4, 'P':5 }}])
data['RegCode'] = enc_RegCode.fit_transform(data[['REGION_CODE']])
del data['REGION_CODE']

In [5]:
#IND_Cat
enc_INDCat= ce.OrdinalEncoder(cols=['IND_Cat'], mapping=[{'col':'IND_Cat', 'mapping':{'Goods-producing':1, 'Service-producing':2 }}])
data['INDCat'] = enc_INDCat.fit_transform(data[['IND_Cat']])
del data['IND_Cat']

In [6]:
#IND
enc_INDCode= ce.OrdinalEncoder(cols=['IND'], mapping=[{'col':'IND', 'mapping':{'11':1, '21':2, '22':3, '23':4, '31-33':5, '48-49':6, '61':7,'62':8, '72':9, '81':10, '91':11,'Multiple':12 }}])
data['INDCode'] = enc_INDCode.fit_transform(data[['IND']])
del data['IND']

In [7]:
#Frac_Level
enc_FrCode= ce.OrdinalEncoder(cols=['Frac_Level'], mapping=[{'col':'Frac_Level', 'mapping':{'Very Low':1, 'Low':2, 'Low-Moderate':3, 'High-Moderate':4, 'High':5, 'Very High':6}}])
data['FRCode'] = enc_FrCode.fit_transform(data[['Frac_Level']])
del data['Frac_Level']

In [8]:
#LB_Level
enc_LBCode= ce.OrdinalEncoder(cols=['LB_Level'], mapping=[{'col':'LB_Level', 'mapping':{'Very Low':1, 'Low':2, 'High':3, 'Very High':4}}])
data['LBCode'] = enc_LBCode.fit_transform(data[['LB_Level']])
del data['LB_Level']

In [9]:
#Sh_Level
enc_ShCode= ce.OrdinalEncoder(cols=['Sh_Level'], mapping=[{'col':'Sh_Level', 'mapping':{'Very Low':1, 'Low':2, 'High':3, 'Very High':4}}])
data['ShCode'] = enc_ShCode.fit_transform(data[['Sh_Level']])
del data['Sh_Level']

In [10]:
#HIC_Level
enc_HICCode= ce.OrdinalEncoder(cols=['HIC_Level'], mapping=[{'col':'HIC_Level', 'mapping':{'Very Low':1, 'Low':2, 'Low-Moderate':3, 'Moderate':4, 'High-Moderate':5, 'High':6, 'Very High':7}}])
data['HICCode'] = enc_HICCode.fit_transform(data[['HIC_Level']])
del data['HIC_Level']

In [11]:
#HIC_Per_Level
enc_HICPerCode= ce.OrdinalEncoder(cols=['HIC_Per_Level'], mapping=[{'col':'HIC_Per_Level', 'mapping':{'Very Low':1, 'Low':2, 'Moderate':3, 'High':4, 'Very High':5}}])
data['HICPerCode'] = enc_HICPerCode.fit_transform(data[['HIC_Per_Level']])
del data['HIC_Per_Level']

In [12]:
#Emp1524_Level
enc_E1524Code= ce.OrdinalEncoder(cols=['Emp1524_Level'], mapping=[{'col':'Emp1524_Level', 'mapping':{'Below Average':1, 'Above Average':2}}])
data['E1524Code'] = enc_E1524Code.fit_transform(data[['Emp1524_Level']])
del data['Emp1524_Level']

In [13]:
#Emp2554_Level
enc_E2554Code= ce.OrdinalEncoder(cols=['Emp2554_Level'], mapping=[{'col':'Emp2554_Level', 'mapping':{'Below Average':1, 'Above Average':2}}])
data['E2554Code'] = enc_E2554Code.fit_transform(data[['Emp2554_Level']])
del data['Emp2554_Level']

In [14]:
#Emp55plus_Level
enc_E55pCode= ce.OrdinalEncoder(cols=['Emp55plus_Level'], mapping=[{'col':'Emp55plus_Level', 'mapping':{'Below Average':1, 'Above Average':2}}])
data['E55pCode'] = enc_E55pCode.fit_transform(data[['Emp55plus_Level']])
del data['Emp55plus_Level']

In [15]:
#Contra_level
enc_ConCode= ce.OrdinalEncoder(cols=['Contra_level'], mapping=[{'col':'Contra_level', 'mapping':{'None':1, 'Low':2, 'Moderate':3, 'High':4}}])
data['ConCode'] = enc_ConCode.fit_transform(data[['Contra_level']])
del data['Contra_level']

In [16]:
list(data.columns)

['Total_Claims',
 'FV_D',
 'FV_M',
 'FV_DATE',
 'VISIT_CODE',
 'WP_ID',
 'WP_NAME',
 'WP_ADDRESS',
 'IND_Name',
 'NAICS',
 'NAICS.DESCR',
 'RegCode',
 'INDCat',
 'INDCode',
 'FRCode',
 'LBCode',
 'ShCode',
 'HICCode',
 'HICPerCode',
 'E1524Code',
 'E2554Code',
 'E55pCode',
 'ConCode']

Split data into 70:30 train / test sets

In [17]:
data.corr()

,Total_Claims,FV_D,FV_M,WP_ID,NAICS,RegCode,INDCat,INDCode,FRCode,LBCode,ShCode,HICCode,HICPerCode,E1524Code,E2554Code,E55pCode,ConCode
Total_Claims,1.000000,0.004856,-0.023986,-0.087243,0.075345,-0.174625,0.344046,0.513242,0.650518,0.713880,0.708448,0.782683,-0.431133,0.141538,-0.421806,-0.380741,-0.004733
FV_D,0.004856,1.000000,-0.008590,0.004067,0.015058,-0.011927,0.010861,0.011827,-0.003539,-0.000561,-0.000528,-0.000169,-0.005592,-0.000188,-0.003353,-0.009755,0.003714
FV_M,-0.023986,-0.008590,1.000000,0.056923,-0.026930,-0.005107,-0.030781,-0.031352,-0.002200,-0.014604,-0.026407,-0.020652,0.040571,0.044217,0.047137,0.037370,-0.045449
WP_ID,-0.087243,0.004067,0.056923,1.000000,-0.203185,-0.136333,-0.230026,-0.186932,0.182139,0.057329,0.047542,0.074783,0.422285,0.442841,0.295419,0.412410,0.025904
NAICS,0.075345,0.015058,-0.026930,-0.203185,1.000000,0.007404,0.889711,0.794775,-0.393203,-0.219402,-0.127373,-0.224333,-0.633120,-0.459755,-0.698649,-0.495043,-0.047415
RegCode,-0.174625,-0.011927,-0.005107,-0.136333,0.007404,1.000000,0.023849,0.003573,-0.276728,-0.244007,-0.255680,-0.251737,-0.065943,-0.059898,-0.017307,-0.100573,-0.083018
INDCat,0.344046,0.010861,-0.030781,-0.230026,0.889711,0.023849,1.000000,0.941944,-0.246693,-0.033140,0.036022,-0.028626,-0.742757,-0.271326,-0.754387,-0.724583,-0.067062
INDCode,0.513242,0.011827,-0.031352,-0.186932,0.794775,0.003573,0.941944,1.000000,-0.074322,0.095027,0.152609,0.132791,-0.765143,-0.118551,-0.800211,-0.681702,-0.050063
FRCode,0.650518,-0.003539,-0.002200,0.182139,-0.393203,-0.276728,-0.246693,-0.074322,1.000000,0.890707,0.879310,0.890958,0.131602,0.399849,0.104802,0.183847,0.033647
LBCode,0.713880,-0.000561,-0.014604,0.057329,-0.219402,-0.244007,-0.033140,0.095027,0.890707,1.000000,0.967687,0.953162,-0.073588,0.224952,-0.005767,-0.018405,0.016861
ShCode,0.708448,-0.000528,-0.026407,0.047542,-0.127373,-0.255680,0.036022,0.152609,0.879310,0.967687,1.000000,0.959041,-0.076842,0.154945,-0.072929,-0.028428,0.002642
HICCode,0.782683,-0.000169,-0.020652,0.074783,-0.224333,-0.251737,-0.028626,0.132791,0.890958,0.953162,0.959041,1.000000,-0.020679,0.262071,-0.055820,-0.005156,0.016888
HICPerCode,-0.431133,-0.005592,0.040571,0.422285,-0.633120,-0.065943,-0.742757,-0.765143,0.131602,-0.073588,-0.076842,-0.020679,1.000000,0.473749,0.771630,0.678633,0.052352
E1524Code,0.141538,-0.000188,0.044217,0.442841,-0.459755,-0.059898,-0.271326,-0.118551,0.399849,0.224952,0.154945,0.262071,0.473749,1.000000,0.369312,0.133639,0.043797
E2554Code,-0.421806,-0.003353,0.047137,0.295419,-0.698649,-0.017307,-0.754387,-0.800211,0.104802,-0.005767,-0.072929,-0.055820,0.771630,0.369312,1.000000,0.480821,0.011580
E55pCode,-0.380741,-0.009755,0.037370,0.412410,-0.495043,-0.100573,-0.724583,-0.681702,0.183847,-0.018405,-0.028428,-0.005156,0.678633,0.133639,0.480821,1.000000,0.076247
ConCode,-0.004733,0.003714,-0.045449,0.025904,-0.047415,-0.083018,-0.067062,-0.050063,0.033647,0.016861,0.002642,0.016888,0.052352,0.043797,0.011580,0.076247,1.000000

In [19]:
#Features used --> features with corr >0.85 are removed  --> INDCat, 'FRCode', 'LBCode', 'ShCode',
Features = ['FV_D', 'FV_M', 'FV_DATE', 'VISIT_CODE','WP_ID','NAICS','RegCode', 'INDCode','HICCode','HICPerCode', 'E1524Code', 'E2554Code', 'E55pCode', 'ConCode']
F_x = data.loc[:, Features]
F_y = data.loc[: , ['Claims_Code']]

In [20]:
F_x.corr()

,FV_D,FV_M,WP_ID,NAICS,RegCode,INDCode,HICCode,HICPerCode,E1524Code,E2554Code,E55pCode,ConCode
FV_D,1.000000,-0.008590,0.004067,0.015058,-0.011927,0.011827,-0.000169,-0.005592,-0.000188,-0.003353,-0.009755,0.003714
FV_M,-0.008590,1.000000,0.056923,-0.026930,-0.005107,-0.031352,-0.020652,0.040571,0.044217,0.047137,0.037370,-0.045449
WP_ID,0.004067,0.056923,1.000000,-0.203185,-0.136333,-0.186932,0.074783,0.422285,0.442841,0.295419,0.412410,0.025904
NAICS,0.015058,-0.026930,-0.203185,1.000000,0.007404,0.794775,-0.224333,-0.633120,-0.459755,-0.698649,-0.495043,-0.047415
RegCode,-0.011927,-0.005107,-0.136333,0.007404,1.000000,0.003573,-0.251737,-0.065943,-0.059898,-0.017307,-0.100573,-0.083018
INDCode,0.011827,-0.031352,-0.186932,0.794775,0.003573,1.000000,0.132791,-0.765143,-0.118551,-0.800211,-0.681702,-0.050063
HICCode,-0.000169,-0.020652,0.074783,-0.224333,-0.251737,0.132791,1.000000,-0.020679,0.262071,-0.055820,-0.005156,0.016888
HICPerCode,-0.005592,0.040571,0.422285,-0.633120,-0.065943,-0.765143,-0.020679,1.000000,0.473749,0.771630,0.678633,0.052352
E1524Code,-0.000188,0.044217,0.442841,-0.459755,-0.059898,-0.118551,0.262071,0.473749,1.000000,0.369312,0.133639,0.043797
E2554Code,-0.003353,0.047137,0.295419,-0.698649,-0.017307,-0.800211,-0.055820,0.771630,0.369312,1.000000,0.480821,0.011580
E55pCode,-0.009755,0.037370,0.412410,-0.495043,-0.100573,-0.681702,-0.005156,0.678633,0.133639,0.480821,1.000000,0.076247
ConCode,0.003714,-0.045449,0.025904,-0.047415,-0.083018,-0.050063,0.016888,0.052352,0.043797,0.011580,0.076247,1.000000

In [21]:
x_tr, x_ts, y_tr, y_ts = train_test_split(F_x, F_y,  train_size = .70, random_state = 23)

In [22]:
#Combine the x and y train set
train = x_tr
train['Claims_Code']= y_tr
train.head()

,FV_D,FV_M,FV_DATE,VISIT_CODE,WP_ID,NAICS,RegCode,INDCode,HICCode,HICPerCode,E1524Code,E2554Code,E55pCode,ConCode,Total_Claims
16809,29,6,2019-06-29,2019-06-29 2093649,2093649,812115,3,10,1,2,1,1,2,1,69
13753,25,2,2019-02-25,2019-02-25 1095872,1095872,812330,2,10,2,2,1,1,2,4,485
10215,19,6,2019-06-19,2019-06-19 2091294,2091294,812190,2,10,2,2,1,1,2,4,485
19163,6,5,2019-05-06,2019-05-06 2029237,2029237,238990,4,4,5,5,2,2,2,1,1309
18670,25,10,2019-10-25,2019-10-25 2125435,2125435,236110,4,4,5,5,2,2,2,3,1309

In [23]:
#Combine the x and y test set
test = x_ts
test['Claims_Code']= y_ts
test.head()

,FV_D,FV_M,FV_DATE,VISIT_CODE,WP_ID,NAICS,RegCode,INDCode,HICCode,HICPerCode,E1524Code,E2554Code,E55pCode,ConCode,Total_Claims
24488,14,2,2019-02-14,2019-02-14 1123343,1123343,212232,5,2,1,3,1,2,1,1,112
15245,10,3,2019-03-10,2019-03-10 2006027,2006027,236110,3,4,2,3,2,2,2,1,652
11082,6,6,2019-06-06,2019-06-06 2088395,2088395,811199,2,10,2,2,1,1,2,4,485
14234,16,5,2019-05-16,2019-05-16 2043065,2043065,236220,2,4,6,4,2,2,2,1,1541
15687,23,10,2019-10-23,2019-10-23 2123856,2123856,236220,3,4,2,3,2,2,2,4,652

In [24]:
train.to_csv('Train_set_CC.csv')
test.to_csv('Test_set_CC.csv')

In [87]:
list(train.columns)

['FV_D',
 'FV_M',
 'FV_DATE',
 'VISIT_CODE',
 'WP_ID',
 'NAICS',
 'RegCode',
 'INDCode',
 'HICCode',
 'HICPerCode',
 'E1524Code',
 'E2554Code',
 'E55pCode',
 'ConCode',
 'Claims_Code']